### ISSUE TITLE
design model & decide persistence route

### ISSUE THREAD

**Issue by spxrogers** [spxrogers/UTimeline#1]
part one is needing a java class that's the representation of the app's user. a `User.java` basically (with all cascading objects). it's straight forward enough.

```
class User {
    Timeline timeline;
    ...
}

class Timeline {
    List<Event> events;
    ...
}

// and so on; blah blah blah
```

part two is deciding how we want to store and cache this to disk. we can go the "normal" route with a SQLite solution. i however would personally prefer we use realm (https://realm.io or https://realm.io/docs/java/latest/). it's largely more performant in comparison and, imo, it's much more elegant and pleasant to interface with.

conversation: go

**Comment by spxrogers** [comment]
cc: @ZachSand @wibergln

**Comment by ZachSand** [comment]
I vote for Realm

**Comment by spxrogers** [comment]
Closed: Model implemented with Paper used for persisting user state.
