### ISSUE TITLE
launch activity

### ISSUE THREAD

**Issue by spxrogers** [spxrogers/UTimeline#2]
single-time activity view shown before the timeline is populated.

**Comment by ZachSand** [comment]
Plans: 
1. Add ../res/drawable directory
2. Add a UT image from the internet to the res/drawable directory as well as a simple 'UTimeline' logo.
   - Possibly just smaller [UT image](https://facultyjobs.utexas.edu/img/phase2/RGB_university_primary.png) at first
   - Could also use a full image like this [UT Tower Image](http://media.cdn.builtinaustin.com/sites/www.builtinaustin.com/files/imagecache/Original/images/utaustin.jpg)
   - Or some other one ...
3. Add XML file 'no_event_startup.xml' (or similarly named) 
   - Depending on the picture used, this could most simply be a vertical Linear Layout with an ImageView at the top containing the logo, the the UT image, then a Button below it with the text 'Add event' within it
4.  In Timeline onCreate() and Timeline onRestoreInstanceState() methods, check to see if the current user has any UTimelineEvent(s) in their events list. 
   - If they do not, setContentView(R.layout.no_event_startup) (or whatever the xml is named)
5. Add an onClickListener for the button on the page that leads the user to the 'Add Event' Page. 
   - Should there be a way to go back to the 'no_event_startup.xml' page for the user? 
     - If not, the 'Add Event' page needs to save the instance state in some way so when the user reopens the app it takes them back to the 'Add Event' page instead of the 'startup' page. 
     - Or some other behavior..

What do you guys think?
@spxrogers @wibergln

**Comment by ZachSand** [comment]
After 80ee13935ff5c5ee94ac7e2c16f5f2b619cea594 Need to: 
1. Add onClickListener to the 'Add First Event' button that navigates the user to the 'Add Event' page (currently this hasn't been created).

**Comment by ZachSand** [comment]
Merged!
